# Generated by Django 2.0.2 on 2020-10-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepic/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awwards.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='webimage',
            field=models.ImageField(null=True, upload_to='webimage/'),
        ),
    ]
