# Generated by Django 2.0.2 on 2020-10-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_auto_20201026_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
    ]
