# Generated by Django 2.0.2 on 2020-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_auto_20201027_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
