# Generated by Django 2.0.2 on 2020-10-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpeg', upload_to='profilepic/'),
        ),
    ]
